project_id_env: "CROWDIN_PROJECT_ID"
api_token_env: "CROWDIN_PERSONAL_TOKEN"
base_path: "."

preserve_hierarchy: false

files:
  - source: /public/locales/zh-CN/*.json
    translation: /public/locales/%locale%/%original_file_name%
