import { BeatArrayToNumber, parseDoublePrecist } from '@/utils/math';
import { BeatArray } from '@/utils/types';

export default class ChartBPM {
  beat: BeatArray;
  beatNum: number;
  bpm: number;

  time: number ;
  timePerBeat: number;
  endBeat: BeatArray;
  endBeatNum: number;
  endTime: number;

  constructor(beat: BeatArray, bpm: number) {
    if (BeatArrayToNumber(beat) < 0) throw new Error('Cannot set a negative beat to BPM!');
    if (bpm <= 0) throw new Error('Cannot set a zero/negative BPM!');

    this.beat = beat;
    this.beatNum = BeatArrayToNumber(this.beat);
    this.bpm = bpm;

    /**
     * NOTE: These will be generated by BPMList automatically,
     * please do not edit them manually!
    */
    this.time = NaN;
    this.timePerBeat = parseDoublePrecist(60 / this.bpm, 6, -1);
    this.endBeat = [ Infinity, 0, 1 ];
    this.endBeatNum = Infinity;
    this.endTime = Infinity;
  }
}
